if(!isGeneric("solve")){
    setGeneric("solve", function(a,b,...) standardGeneric("solve"))
}
############################################################################
# Access methods
############################################################################

if(!isGeneric("name")) 
    setGeneric("name", function(object) standardGeneric("name"))

if(!isGeneric("getp")) 
   setGeneric("getp", function(object) standardGeneric("getp"))
if(!isGeneric("getq")) 
   setGeneric("getq", function(object) standardGeneric("getq"))

if(!isGeneric("getF")) 
   setGeneric("getF", function(object) standardGeneric("getF"))
if(!isGeneric("getZ")) 
   setGeneric("getZ", function(object) standardGeneric("getZ"))
if(!isGeneric("getQ")) 
   setGeneric("getQ", function(object) standardGeneric("getQ"))
if(!isGeneric("getV")) 
   setGeneric("getV", function(object) standardGeneric("getV"))
if(!isGeneric("geta")) 
   setGeneric("geta", function(object) standardGeneric("geta"))
if(!isGeneric("getS")) 
   setGeneric("getS", function(object) standardGeneric("getS"))
if(!isGeneric("time")) 
   setGeneric("time", function(x,...) standardGeneric("time"))

if(!isGeneric("SSM")) 
   setGeneric("SSM", function(object, ...) standardGeneric("SSM"))
if(!isGeneric("Y")) 
   setGeneric("Y", function(object, ...) standardGeneric("Y"))
if(!isGeneric("X.filtered")) 
   setGeneric("X.filtered", function(object, ...) standardGeneric("X.filtered"))
if(!isGeneric("X.predicted")) 
   setGeneric("X.predicted", function(object, ...) standardGeneric("X.predicted"))
if(!isGeneric("Cov.filtered")) 
   setGeneric("Cov.filtered", function(object, ...) standardGeneric("Cov.filtered"))
if(!isGeneric("Cov.predicted")) 
   setGeneric("Cov.predicted", function(object, ...) standardGeneric("Cov.predicted"))
if(!isGeneric("Kalman.Gain")) 
   setGeneric("Kalman.Gain", function(object, ...) standardGeneric("Kalman.Gain"))
if(!isGeneric("X.rob.filtered")) 
   setGeneric("X.rob.filtered", function(object, ...) standardGeneric("X.rob.filtered"))
if(!isGeneric("X.rob.predicted")) 
   setGeneric("X.rob.predicted", function(object, ...) standardGeneric("X.rob.predicted"))
if(!isGeneric("Cov.rob.filtered")) 
   setGeneric("Cov.rob.filtered", function(object, ...) standardGeneric("Cov.rob.filtered"))
if(!isGeneric("Cov.rob.predicted")) 
   setGeneric("Cov.rob.predicted", function(object, ...) standardGeneric("Cov.rob.predicted"))
if(!isGeneric("Kalman.rob.Gain")) 
   setGeneric("Kalman.rob.Gain", function(object, ...) standardGeneric("Kalman.rob.Gain"))
if(!isGeneric("rob.correction.ctrl")) 
   setGeneric("rob.correction.ctrl", function(object, ...) standardGeneric("rob.correction.ctrl"))
if(!isGeneric("rob.prediction.ctrl")) 
   setGeneric("rob.prediction.ctrl", function(object, ...) standardGeneric("rob.prediction.ctrl"))
if(!isGeneric("IndIO")) 
   setGeneric("IndIO", function(object, ...) standardGeneric("IndIO"))
if(!isGeneric("IndAO")) 
   setGeneric("IndAO", function(object, ...) standardGeneric("IndAO"))
if(!isGeneric("nsim")) 
   setGeneric("nsim", function(object, ...) standardGeneric("nsim"))
if(!isGeneric("RNGstate")) 
   setGeneric("RNGstate", function(object, ...) standardGeneric("RNGstate"))
if(!isGeneric("Cov.rob.filtered.sim")) 
   setGeneric("Cov.rob.filtered.sim", function(object, ...) standardGeneric("Cov.rob.filtered.sim"))
if(!isGeneric("Cov.rob.predicted.sim")) 
   setGeneric("Cov.rob.predicted.sim", function(object, ...) standardGeneric("Cov.rob.predicted.sim"))
if(!isGeneric("init")) 
   setGeneric("init", function(object, ...) standardGeneric("init"))
if(!isGeneric("predict")) 
   setGeneric("predict", function(object, ...) standardGeneric("predict"))
if(!isGeneric("correct")) 
   setGeneric("correct", function(object, ...) standardGeneric("correct"))
if(!isGeneric("init.rob")) 
   setGeneric("init.rob", function(object, ...) standardGeneric("init.rob"))
if(!isGeneric("name.rob")) 
   setGeneric("name.rob", function(object, ...) standardGeneric("name.rob"))
if(!isGeneric("predict.rob")) 
   setGeneric("predict.rob", function(object, ...) standardGeneric("predict.rob"))
if(!isGeneric("correct.rob")) 
   setGeneric("correct.rob", function(object, ...) standardGeneric("correct.rob"))
if(!isGeneric("controls")) 
   setGeneric("controls", function(object, ...) standardGeneric("controls"))
                              
############################################################################
# Replacement methods
############################################################################

if(!isGeneric("name<-")) 
    setGeneric("name<-", 
                function(object, value) standardGeneric("name<-"))

if(!isGeneric("setp<-")) 
   setGeneric("setp<-", function(object, value) standardGeneric("setp<-"))
if(!isGeneric("setq<-")) 
   setGeneric("setq<-", function(object, value) standardGeneric("setq<-"))

if(!isGeneric("setF<-")) 
   setGeneric("setF<-", function(object, value) standardGeneric("setF<-"))
if(!isGeneric("setZ<-")) 
   setGeneric("setZ<-", function(object, value) standardGeneric("setZ<-"))
if(!isGeneric("setQ<-")) 
   setGeneric("setQ<-", function(object, value) standardGeneric("setQ<-"))
if(!isGeneric("setV<-")) 
   setGeneric("setV<-", function(object, value) standardGeneric("setV<-"))
if(!isGeneric("seta<-")) 
   setGeneric("seta<-", function(object, value) standardGeneric("seta<-"))
if(!isGeneric("setS<-")) 
   setGeneric("setS<-", function(object, value) standardGeneric("setS<-"))
if(!isGeneric("time<-")) 
   setGeneric("time<-", function(x, value) standardGeneric("time<-"))

if(!isGeneric(".make.project")) 
setGeneric(".make.project",function(object, ...) standardGeneric(".make.project"))

if(!isGeneric("kalman")) 
setGeneric("kalman",function(smooth, ...) standardGeneric("kalman"))

if(!isGeneric("kalmanRob")) 
setGeneric("kalmanRob",function(method, smooth, ...) standardGeneric("kalmanRob"))
